/*
 * Copyright 2007-2013 VTT Biotechnology
 * This file is part of Guineu.
 *
 * Guineu is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * Guineu is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Guineu; if not, write to the Free Software Foundation, Inc., 51 Franklin St,
 * Fifth Floor, Boston, MA 02110-1301 USA
 */
package guineu.modules.dataanalysis.Ttest;

import guineu.data.Dataset;
import guineu.main.GuineuCore;
import guineu.util.dialogs.ExitCode;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author SCSANDRA
 */
public class TtestDataDialog extends JDialog {

        private Logger logger = Logger.getLogger(this.getClass().getName());
        private ExitCode exit = ExitCode.UNKNOWN;

        /**
         * Creates new form TtestDataDialog
         */
        public TtestDataDialog(Dataset dataset) {
                super(GuineuCore.getDesktop().getMainFrame(),
                        "Please select a experiment groups to do the t-test...", true);

                logger.finest("Displaying experiment open dialog");
                initComponents();

                for (String parameters : dataset.getParametersName()) {
                        if (!parameters.equals("Samples")) {
                                this.jComboBox1.addItem(parameters);
                        }
                }


                if (dataset.getParametersName().isEmpty()) {
                        this.jComboBox1.addItem("No parameters available");
                }
        }

        public String getParameter() {
                return (String) jComboBox1.getSelectedItem();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel5 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox();
                jPanel3 = new javax.swing.JPanel();
                jButtonOK = new javax.swing.JButton();
                jButtonClose = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(270, 176));

                jLabel1.setText("Select Parameter");
                jPanel5.add(jLabel1);

                jPanel5.add(jComboBox1);

                getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

                jButtonOK.setText(" Ok ");
                jButtonOK.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonOKActionPerformed(evt);
                        }
                });
                jPanel3.add(jButtonOK);

                jButtonClose.setText("Cancel");
                jButtonClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCloseActionPerformed(evt);
                        }
                });
                jPanel3.add(jButtonClose);

                jButton1.setText("Help");
                jPanel3.add(jButton1);

                getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

                pack();
        }// </editor-fold>//GEN-END:initComponents
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
            exit = ExitCode.OK;
            dispose();
}//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
            exit = ExitCode.CANCEL;
            dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

        public ExitCode getExitCode() {
                return exit;
        }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButtonClose;
        private javax.swing.JButton jButtonOK;
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel5;
        // End of variables declaration//GEN-END:variables
}
