/*
 * GetAlignmentParameters.java
 *
 * Created on 18 April 2008, 10:16
 */

package guineu.modules.filter.Alignment;

import guineu.main.GuineuCore;
import guineu.util.dialogs.ExitCode;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author  SCSANDRA
 */
public class GetAlignmentParameters extends JDialog  {
    private Logger logger = Logger.getLogger(this.getClass().getName());

    AlignmentParameters AP;
    private ExitCode exit = ExitCode.UNKNOWN;
    /** Creates new form GetAlignmentParameters */
    public GetAlignmentParameters(AlignmentParameters AP) { 
        super(GuineuCore.getDesktop().getMainFrame(),
				"Please select the parameters...", true);
        logger.finest("Displaying alignment dialog");                        
        this.setSize(430, 307);
        initComponents();
        this.AP = AP;
        this.setInitialValues();         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldMinNumberPoints = new javax.swing.JTextField();
        jTextFieldMargin = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButtonHelpMinimThreshold = new javax.swing.JButton();
        jButtonHelpMargin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextFieldOptimizationIterations = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonHelpOptimizationIterations = new javax.swing.JButton();
        jButtonHelpLinealDistribution = new javax.swing.JButton();
        jButtonHelpCurveDistribution = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonSet = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("RANSAC Parameters"));

        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 20));

        jLabel3.setText("Threshold (t)");
        jPanel3.add(jLabel3);

        jLabel8.setText("Margin:");
        jPanel3.add(jLabel8);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 10, 10));
        jPanel4.add(jTextFieldMinNumberPoints);
        jPanel4.add(jTextFieldMargin);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jButtonHelpMinimThreshold.setText("Help");
        jButtonHelpMinimThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpMinimThresholdActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonHelpMinimThreshold);

        jButtonHelpMargin.setText("Help");
        jButtonHelpMargin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpMarginActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonHelpMargin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Optimization"));

        jPanel7.setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        jLabel4.setText("Optimization Iterations:");
        jPanel7.add(jLabel4);

        jLabel5.setText("Lineal Distribution:");
        jPanel7.add(jLabel5);

        jLabel6.setText("Curve Distribution:");
        jPanel7.add(jLabel6);

        jPanel8.setLayout(new java.awt.GridLayout(3, 0, 0, 10));
        jPanel8.add(jTextFieldOptimizationIterations);

        buttonGroup2.add(jRadioButton1);
        jPanel8.add(jRadioButton1);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jPanel8.add(jRadioButton2);

        jPanel9.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jButtonHelpOptimizationIterations.setText("Help");
        jButtonHelpOptimizationIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpOptimizationIterationsActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonHelpOptimizationIterations);

        jButtonHelpLinealDistribution.setText("Help");
        jButtonHelpLinealDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpLinealDistributionActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonHelpLinealDistribution);

        jButtonHelpCurveDistribution.setText("Help");
        jButtonHelpCurveDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpCurveDistributionActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonHelpCurveDistribution);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonSet.setText("Set");
        jButtonSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSet);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, 0, 311, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHelpMarginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpMarginActionPerformed
        JOptionPane.showMessageDialog(null, "Number maxim of seconds that we admit as a margin from the ransac line.", "Help",JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jButtonHelpMarginActionPerformed

    private void jButtonHelpMinimThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpMinimThresholdActionPerformed
        JOptionPane.showMessageDialog(null, ".", "Help",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonHelpMinimThresholdActionPerformed

    private void jButtonHelpOptimizationIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpOptimizationIterationsActionPerformed
        JOptionPane.showMessageDialog(null, "Number of iterations in the optimization algorithm.", "Help",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonHelpOptimizationIterationsActionPerformed

    private void jButtonHelpLinealDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpLinealDistributionActionPerformed
        JOptionPane.showMessageDialog(null, "The most optimal alignment is the one which has the most lineal distribution.", "Help",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonHelpLinealDistributionActionPerformed

    private void jButtonHelpCurveDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpCurveDistributionActionPerformed
        JOptionPane.showMessageDialog(null, "The most optimal alignment is the one which has more points in a curve distribution.", "Help",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonHelpCurveDistributionActionPerformed

    private void jButtonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetActionPerformed
        this.setParameters();
        exit = ExitCode.OK;
        dispose();
    }//GEN-LAST:event_jButtonSetActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        exit = ExitCode.CANCEL;
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed
    
    public ExitCode getExitCode(){
        return exit;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonHelpCurveDistribution;
    private javax.swing.JButton jButtonHelpLinealDistribution;
    private javax.swing.JButton jButtonHelpMargin;
    private javax.swing.JButton jButtonHelpMinimThreshold;
    private javax.swing.JButton jButtonHelpOptimizationIterations;
    private javax.swing.JButton jButtonSet;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextFieldMargin;
    private javax.swing.JTextField jTextFieldMinNumberPoints;
    private javax.swing.JTextField jTextFieldOptimizationIterations;
    // End of variables declaration//GEN-END:variables

    private void setInitialValues() {
        this.jTextFieldOptimizationIterations.setText(String.valueOf(this.AP.getParameterValue(AlignmentParameters.OptimizationIterations)));
        this.jTextFieldMinNumberPoints.setText(String.valueOf(this.AP.getParameterValue(AlignmentParameters.NMinPoints)));
          this.jTextFieldMargin.setText(String.valueOf(this.AP.getParameterValue(AlignmentParameters.Margin)));
        if((Boolean)this.AP.getParameterValue(AlignmentParameters.curve)){
            this.jRadioButton2.setSelected(true);
        }else{
            this.jRadioButton1.setSelected(true);
        }
        
    }
    // End of variables declaration

    private void setParameters() {
        try{
            this.AP.setParameterValue(AlignmentParameters.NMinPoints, Double.valueOf(this.jTextFieldMinNumberPoints.getText()));
            this.AP.setParameterValue(AlignmentParameters.Margin, Double.valueOf(this.jTextFieldMargin.getText()));
            this.AP.setParameterValue(AlignmentParameters.OptimizationIterations, Integer.valueOf(this.jTextFieldOptimizationIterations.getText()));
            if(this.jRadioButton1.isSelected()){
                this.AP.setParameterValue(AlignmentParameters.curve, false);
            }else{
                this.AP.setParameterValue(AlignmentParameters.curve, true);
            }
            
        }catch(Exception exception){
            exception.printStackTrace();
        }
    }

   
}
