/*
 * TtestDataDialog.java
 *
 * Created on 14 September 2008, 13:10
 */

package guineu.modules.statistics.UPGMAClustering;

import guineu.data.impl.SimpleLCMSDataset;
import guineu.main.GuineuCore;
import guineu.util.dialogs.ExitCode;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author  SCSANDRA
 */
public class UPGMADataDialog extends JDialog {
    private Logger logger = Logger.getLogger(this.getClass().getName());
    private SimpleLCMSDataset dataset;
    private UPGMADataModel group1, group2;
    private ExitCode exit = ExitCode.UNKNOWN;
    
    /** Creates new form TtestDataDialog */
    public UPGMADataDialog(SimpleLCMSDataset dataset) {
        super(GuineuCore.getDesktop().getMainFrame(),
				"Please select a experiment groups to do the t-test...", true);

        logger.finest("Displaying experiment open dialog");
        this.dataset = dataset;        
        initComponents();
        this.group1 = new UPGMADataModel("Group1 - Experiment Names");
        this.group2 = new UPGMADataModel("Group1 - Experiment Names");
        this.jTablefrom.setModel(group1);
        this.jTablefrom.createToolTip();
        this.jTableto.setModel(group2);
        this.setValuesTable();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablefrom = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonizq = new javax.swing.JButton();
        jButtonder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTablefrom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selected Experiment "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablefrom.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTablefrom);

        jPanel1.add(jScrollPane1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jButtonizq.setText(">>");
        jButtonizq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonizqActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonizq);

        jButtonder.setText("<<");
        jButtonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonderActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonder);

        jPanel1.add(jPanel2);

        jTableto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Non selected Experiments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableto.setShowHorizontalLines(false);
        jScrollPane2.setViewportView(jTableto);

        jPanel1.add(jScrollPane2);

        jLabel1.setText("Select the experiments");

        jButtonOK.setText("Ok");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOK);

        jButtonClose.setText("Cancel");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(703, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        exit = ExitCode.OK;
        dispose();
}//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        exit = ExitCode.CANCEL;
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonizqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonizqActionPerformed
        int[] selRows = this.jTablefrom.getSelectedRows();        
        for(int i = 0; i < selRows.length; i++){
            if(!this.group1.getValueAt(selRows[i], 0).isEmpty()){               
                this.group2.addRows((String)this.group1.getValueAt(selRows[i], 0));                
                this.group1.removeRow(selRows[i]);
            }
        }
        this.group1.reconstruct();
        this.jTablefrom.revalidate();
        this.jTableto.revalidate();
}//GEN-LAST:event_jButtonizqActionPerformed

    private void jButtonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonderActionPerformed
        int[] selRows = this.jTableto.getSelectedRows();
        for(int i = 0; i < selRows.length; i++){
            if(!this.group2.getValueAt(selRows[i], 0).isEmpty()){
                this.group1.addRows((String)this.group2.getValueAt(selRows[i], 0));         
                this.group2.removeRow(selRows[i]);
            }
        }
        this.group2.reconstruct();
        this.jTablefrom.revalidate();
        this.jTableto.revalidate();
}//GEN-LAST:event_jButtonderActionPerformed
    
    public ExitCode getExitCode(){
        return exit;
    }
    
    public String[] getGroup1(){
        String[] sgroup1 = new String[this.jTablefrom.getRowCount()];
        for(int i = 0; i < this.jTablefrom.getRowCount(); i++){
            sgroup1[i] = this.jTablefrom.getValueAt(i, 0).toString();
        }
        return sgroup1;
    }
    
    public String[] getGroup2(){
        String[] sgroup2 = new String[this.jTableto.getRowCount()];
        for(int i = 0; i < this.jTableto.getRowCount(); i++){
            sgroup2[i] = this.jTableto.getValueAt(i, 0).toString();
        }
        return sgroup2;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonder;
    private javax.swing.JButton jButtonizq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablefrom;
    private javax.swing.JTable jTableto;
    // End of variables declaration//GEN-END:variables

    private void setValuesTable() {        
       /* for(Experiment experiment: dataset.getExperiments()){
            this.group1.addRows(experiment.getExperimentName());
        }*/
    }
    
}
