/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addParameterDialog.java
 *
 * Created on Jun 23, 2010, 3:21:10 PM
 */

package guineu.modules.configuration.parameters;

import guineu.util.dialogs.ExitCode;

/**
 *
 * @author scsandra
 */
public class AddParameterDialog extends javax.swing.JDialog {

    private ExitCode exitCode = ExitCode.UNKNOWN;
    private String name;

    /** Creates new form addParameterDialog */
    public AddParameterDialog() {      
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Parameter Name: ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        tfPName.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel1.add(tfPName, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnOk.setText("Ok ");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel2.add(btnOk);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        name = tfPName.getText();
        exitCode = ExitCode.OK;
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Method for reading exit code
     */
    public ExitCode getExitCode() {
        return exitCode;
    }

    public String getParameterName(){
        return name;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfPName;
    // End of variables declaration//GEN-END:variables

}
